### Read Customers entity
GET http://localhost:4004/odata/v4/customer/Customers


### Create data in Customers entity
POST http://localhost:4004/odata/v4/customer/Customers
Content-Type: application/json

{
  "firstname": "sam2test_",
  "lastname": "abc2",
  "customerId": "9574028b-f50a-439a-91a4-d84e570ac6a1",
  "email": "sam2@gamil.com",
  "address": "1234",
  "phoneno": 1234566789,
  "status": 2
}

### Update using patch
PATCH http://localhost:4004/odata/v4/customer/Customers/9574028b-f50a-439a-91a4-d84e570ac6a1
Content-Type: application/json

{
  "address" : "Bengaluru"
}


### Delete a data from the database
DELETE http://localhost:4004/odata/v4/customer/Customers/9574028b-f50a-439a-91a4-d84e570ac6a1
